name: CI

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - head
          - 3.3
          - 3.2
          - 3.1
        rails-version:
          - edge
          - 7.1
          - "7.0"
          - 6.1
        exclude:
          - ruby-version: head
            rails-version: "7.0"
          - ruby-version: head
            rails-version: 6.1
          - ruby-version: 3.3
            rails-version: "7.0"
          - ruby-version: 3.2
            rails-version: "7.0"
          - ruby-version: 3.1
            rails-version: "7.0"
    env:
      RAILS_VERSION: "${{ matrix.rails-version }}"
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby-version }}"
          bundler-cache: true
      - run: bundle exec rspec
