name: CI

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby-version: '3.2'
            rails-version: '6.1'
          - ruby-version: '3.2'
            rails-version: '7.0'
          - ruby-version: '3.3'
            rails-version: '7.1'
    env:
      RAILS_VERSION: "${{ matrix.rails-version }}"
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby-version }}"
          bundler-cache: true
      - run: bundle exec rspec
